/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as PageRouteImport } from './app/page'
import { Route as FeaturesPageRouteImport } from './app/features/page'

const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesPageRoute = FeaturesPageRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/features/': typeof FeaturesPageRoute
}
export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/features': typeof FeaturesPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/features/': typeof FeaturesPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/features/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/features'
  id: '__root__' | '/' | '/features/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  FeaturesPageRoute: typeof FeaturesPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  FeaturesPageRoute: FeaturesPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
